[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# 1. Main Production Build (compiles all src files)
[env:prod]
extends = env:esp32dev
build_src_filter = +<*.cpp> +<drivers/*.cpp>

# 2. Wi-Fi Standalone Test Build
[env:test_wifi]
extends = env:esp32dev
build_src_filter = +<../test/test_wifi/test_wifi.cpp>

# 3. ECG Standalone Test Build
[env:test_ecg]
extends = env:esp32dev
build_src_filter = +<../test/test_ecg/test_ecg.cpp>

[env:test_abnormalities]
extends = env:esp32dev
build_src_filter = +<../test/test_abnormalities/test_abnormalities.cpp> +<ecg_processor.cpp>

[env:test_api]
extends = env:esp32dev
build_src_filter = +<../test/test_api/test_api.cpp> +<network.cpp> +<buzzer.cpp> +<led_status.cpp>

[env:test_buzzer]
extends = env:esp32dev
build_src_filter = +<../test/test_buzzer/test_buzzer.cpp>

[env:test_recorder]
extends = env:esp32dev
build_src_filter = +<../test/test_recorder/test_recorder.cpp>

[env:test_accuracy]
extends = env:esp32dev
build_src_filter = +<../test/test_accuracy/test_accuracy.cpp> +<ecg_processor.cpp> +<signal_quality.cpp>

[env:test_spandan]
extends = env:esp32dev
build_src_filter = +<../test/test_spandan/test_spandan.cpp> +<ecg_processor.cpp> +<spandan.cpp>